version: '3'
services:
  learninglocker:
    build: learninglocker
    container_name: learninglocker
    depends_on:
      - learninglocker_mongo
      - learninglocker_redis
    ports:
      - "3000:3000"
      - "8080:8080"
      - "8081:8081"
    working_dir: /usr/local/src/learninglocker
    command: bash -c "source ~/.bashrc && yarn migrate && pm2 start pm2/all.json && cd ../xapi-service && pm2 start pm2/xapi.json && pm2 logs"
  learninglocker_mongo:
    image: mongo:4.0.27
    container_name: learninglocker_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./learninglocker/mongo_data:/data/db
  learninglocker_redis:
    image: redis:5.0.14
    container_name: learninglocker_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./learninglocker/redis_data:/data
    command: redis-server --appendonly yes